### ISSUE TITLE
[REQ] BakaBT

### ISSUE THREAD

**Issue by Ether009** [zone117x/Jackett#1]
Would love bakabt support for this.

http://bakabt.me/browse.php is the site. Public signup, but you dont need to sign up, there's just a delay if you do not sign up.

**Comment by da3dsoul** [comment]
BakaBT has a client whitelist. Unless this pretends to be something else, it won't work.

**Comment by Ether009** [comment]
Umm... Sonarr isn't a torrent client by itself. It only gives the torrent to a client. Only the tracker portion of BakaBT has a whitelist, the site itself, which Sonarr uses, does not have any whitelist. So no, there's no need to pretend to be something else.

**Comment by da3dsoul** [comment]
Ah, I see. My mistake.

**Comment by Kayomani** [comment]
Implemented in develop, available in the next release.
