### ISSUE TITLE
Morethan.tv Configuration Failed

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#10]
When I try to add morethan.tv as an indexer I get a message saying configuration failed. I have double checked username and password.

**Comment by zone117x** [comment]
There are various error related to SSL and mono, I think this is one of them. I'm working on a fix.

**Comment by sea3pea0** [comment]
Actually in this case I am running Jackett from a windows machine. I am running Jackett on a windows machine until it is working with mono. I also experienced a problem adding BitMeTV. I get the following message after pressing okay to add the indexer:  Configuration failed: String was not recognized as a valid DateTime.

**Comment by zone117x** [comment]
MoreThan.tv should work on Windows in latest release. https://github.com/zone117x/Jackett/releases
I'll close this issue since we already have another issue for mono ssl errors.
