### ISSUE TITLE
Torrent Leech Error v0.5

### ISSUE THREAD

**Issue by wookienz** [zone117x/Jackett#109]
running on a fedora 21 system with launch command of: mono JackettConsole.exe -t -l -c

Output:
>07-26 09:21:22 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose 
07-26 09:21:44 Info   http://192.168.3.18:9117/admin/configure_indexer 
System.Web.Http.Request:   http://192.168.3.18:9117/admin/configure_indexer
07-26 09:21:44 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
{"indexer":"torrentleech","name":"TorrentLeech","config":{"username":"auser","password":"apassword"}}
07-26 09:21:44 Debug POST: http://192.168.3.18:9117/admin/configure_indexer 
07-26 09:21:44 Debug Body: {"indexer":"torrentleech","name":"TorrentLeech","config":{"username":"auser","password":"apassword"}} 
07-26 09:21:44 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
07-26 09:21:44 Info DefaultHttpControllerSelector SelectController Admin 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Admin
07-26 09:21:44 Info HttpControllerDescriptor CreateController  
System.Web.Http.Controllers: HttpControllerDescriptor CreateController 
07-26 09:21:44 Info DefaultHttpControllerActivator Create  
System.Web.Http.Controllers: DefaultHttpControllerActivator Create 
07-26 09:21:44 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
System.Web.Http.Controllers: DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
07-26 09:21:44 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
System.Web.Http.Controllers: HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
07-26 09:21:44 Info AdminController ExecuteAsync  
System.Web.Http.Controllers: AdminController ExecuteAsync 
07-26 09:21:44 Info ApiControllerActionSelector SelectAction  
System.Web.Http.Action: ApiControllerActionSelector SelectAction 
07-26 09:21:44 Info ApiControllerActionSelector SelectAction Selected action 'Configure()' 
System.Web.Http.Action: ApiControllerActionSelector SelectAction Selected action 'Configure()'
07-26 09:21:44 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
07-26 09:21:44 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
07-26 09:21:44 Info HttpActionBinding ExecuteBindingAsync  
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync 
07-26 09:21:44 Info HttpActionBinding ExecuteBindingAsync  
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync 
07-26 09:21:44 Info ApiControllerActionInvoker InvokeActionAsync Action='Configure()' 
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
07-26 09:21:44 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()' 
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
07-26 09:22:00 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
07-26 09:22:00 Info ApiControllerActionInvoker InvokeActionAsync  
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync 
07-26 09:22:00 Info AdminController ExecuteAsync  
System.Web.Http.Controllers: AdminController ExecuteAsync 
{"name":"TorrentLeech","result":"error","error":"Error getting response stream (ReadDone1): ReceiveFailure"}
07-26 09:22:00 Debug Response: {"name":"TorrentLeech","result":"error","error":"Error getting response stream (ReadDone1): ReceiveFailure"} 
07-26 09:22:00 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
07-26 09:22:00 Info   Content-type='application/json; charset=utf-8', content-length=108 
System.Web.Http.Request:   Content-type='application/json; charset=utf-8', content-length=108
07-26 09:22:00 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose 
07-26 09:22:00 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose 

Web interface message: 
>Configuration failed: Error getting response stream (ReadDone1): ReceiveFailure

Same error with -c switch on or off.

yum info libcurl:
>Name        : libcurl
Arch        : x86_64
Version     : 7.37.0
Release     : 14.fc21

yum info mono
>Mono JIT compiler version 4.0.1

thanks.

EDIT: correct log output

**Comment by Kayomani** [comment]
Looks ok to me on Fedora 21 in develop.  Can you confirm your curl --version matches?

[kayomani@localhost Debug]$ mono JackettConsole.exe
07-30 18:38:32 Info Starting Jackett 0.6.0.0
07-30 18:38:32 Info Using HTTP Client: UnixLibCurlWebClient
07-30 18:38:32 Info LibCurl initOk
07-30 18:38:32 Info LibCurl version libcurl/7.37.0 NSS/3.18 Basic ECC zlib/1.2.8 libidn/1.31 libssh2/1.5.0
07-30 18:38:32 Info Starting web server at http://*:9117/
07-30 18:39:03 Info Found 100 releases from TorrentLeech
[kayomani@localhost Debug]$ curl --version
curl 7.37.0 (x86_64-redhat-linux-gnu) libcurl/7.37.0 NSS/3.18 Basic ECC zlib/1.2.8 libidn/1.31 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz Metalink

**Comment by wookienz** [comment]
$ curl --version
curl 7.37.0 (x86_64-redhat-linux-gnu) libcurl/7.37.0 NSS/3.18 Basic ECC zlib/1.2.8 libidn/1.28 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz Metalink

**Comment by Kayomani** [comment]
Sent you a link on irc its not been well tested yet but it'll fix torrent leech for you.

**Comment by Kayomani** [comment]
Yeah you have the bugged libcurl.  Here is a link to a release candidate for 0.6, it'll fix torrent leech but keep in mind there has been limited testing done.  Let us know if it fixes or if you have any other issues.

 http://no-ho.com/Jackett/Jackett.0.6pre.zip

**Comment by zone117x** [comment]
@Kayomani can we close this issue now?

**Comment by Kayomani** [comment]
Yeah but its really up to @wookienz to test.

**Comment by Kayomani** [comment]
Having tested this quite a bit i am going to close this.  If you test and still have the issue reply to reopen.

**Comment by wookienz** [comment]
works, thanks.
