### ISSUE TITLE
[Req] Showrss support

### ISSUE THREAD

**Issue by jac5** [zone117x/Jackett#11]
Could you add support for Showrss.  Here is the complete feed: http://showrss.info/feeds/all.rss

**Comment by g10rgio** [comment]
I would like to see this too :)

**Comment by damwthomas** [comment]
I've started writing this, only problem with showrss is that you can't really search.
I'll add the all.rss and i'll try making it possible to add your custom schedule link.

**Comment by damwthomas** [comment]
all.rss has been added, the custom rss can be added directly in sonarr.

**Comment by zone117x** [comment]
Closing this issue.
