### ISSUE TITLE
How to launch on Linux?

### ISSUE THREAD

**Issue by my95z34** [zone117x/Jackett#110]
So, I've been running Jackett on Linux for quite some time now, but I haven't upgraded in awhile.  I believe the last version I downloaded was 0.2.7.

But, now I can't figure out what to run in mono since there are a bunch of .exe files.  Any help?

TIA!

**Comment by whodean** [comment]
Similarly, which file do I run with Mono on Mac?

**Comment by wookienz** [comment]
i just upgraded to 0.5. I run "mono JackettConsole.exe" inside a screen session.

**Comment by my95z34** [comment]
I've ran JackettConsole.exe but it says that the UI is only available on localhost, so I cannot access it.  I have it running inside of a jail on FreeNAS, which means it's headless.  Soooooo, yeah.

**Comment by wookienz** [comment]
I run jacketconsole.exe on a headless machine, it is available on my network. It listens on all interfaces.

Check config?

On 26 July 2015 11:59:57 pm GMT+08:00, my95z34 <notifications@github.com> wrote:
>I've ran JackettConsole.exe but it says that the UI is only available
>on localhost, so I cannot access it.  I have it running inside of a
>jail on FreeNAS, which means it's headless.  Soooooo, yeah.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zone117x/Jackett/issues/110#issuecomment-125011186

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by my95z34** [comment]
When running the console exe, I get this:
root@jackett:/jackett/Jackett # mono JackettConsole.exe
07-26 12:13:44 Info Starting Jackett 0.5.0.0 
07-26 12:13:44 Info Starting web server at http://127.0.0.1:9117/ 
07-26 12:13:44 Info Running in console mode! 

And it is not visible to any other devices.  I looked at the JackettConsole.exe.config and I don't see anything in there regarding the IP, or anything for that matter.

**Comment by Kayomani** [comment]
Normally I say use --ListenPublic as is described by --help .. but there is a small issue preventing that from working in the last release which i just fixed.

What you can do is do mono "JackettConsole.exe -p 9118" which changes the port and saves the configuration file.  Quit Jacket then go ~/.config/Jackett/ServerConfig.json and change "AllowExternal": true and the port back.

**Comment by my95z34** [comment]
Thank you @Kayomani that worked perfectly.
