### ISSUE TITLE
[REQ] immortalseed.me

### ISSUE THREAD

**Issue by ca53395** [zone117x/Jackett#111]

**Comment by Kayomani** [comment]
I don't have access to this one but I can implement it if I can get an invite?

**Comment by ca53395** [comment]
I can send you an invite link...just email me at ca53395@hotmail.com

**Comment by Kayomani** [comment]
Sent you a mail.

**Comment by ca53395** [comment]
Sorry about that...it got scooped up into my spam folder for some reason and I missed it. Just sent the invite. Thanks!

**Comment by Kayomani** [comment]
Implemented in develop, will be available in the next release.
