### ISSUE TITLE
Speed.cd error v0.5

### ISSUE THREAD

**Issue by subzero79** [zone117x/Jackett#112]
Running on Debian 7.8, with 

mono -V
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c)

executing Jackett as:

mono JackettConsole.exe -t -l

Output:

http://pastebin.com/wYDHKDZx

Error in GUI

"Configuration failed: Error getting response stream (ReadDone1): ReceiveFailure"

Probably related to #109

**Comment by zone117x** [comment]
This should be fixed in latest release. Please test and let us know. Closing this issue.
