### ISSUE TITLE
Curl dependencies should be checked on launch (mono only)

### ISSUE THREAD

**Issue by zone117x** [zone117x/Jackett#114]

**Comment by Kayomani** [comment]
Curl it now initialized at launch if its being used and displays the version including openssl version.

**Comment by Kayomani** [comment]
Perhaps we should verify a certain openssl version or something.

Thoughts?

**Comment by zone117x** [comment]
For a lot of the trackers TSL3.0 is required, but looking through the OpenSSL release notes https://www.openssl.org/news/openssl-notes.html I didn't come to any conclusions. What are the odds someone will have to old of a version installed?

**Comment by Kayomani** [comment]
The app now checks and displays the libcurl version on start when running on linux.

After my discovery and resolution of the SSL issue yesterday I am going to close this issue as I don't think it is required.  I don't believe the OpenSSL version matters too much and if its a bugged on there is now a workaround.
