### ISSUE TITLE
Chrome blocking Beta Release as malicious

### ISSUE THREAD

**Issue by TeRmInAlCrAzY** [zone117x/Jackett#116]
Hi,

Using Chrome Version 44.0.2403.107 m, on Windows 7 Home Premium.

Attempting to download either Jackett.v0.5.1.Windows.Installer.exe, or Jackett.v0.5.1.zip from https://github.com/zone117x/Jackett/releases/tag/v0.5.1 results in the error "??? is malicious, and Chrome has blocked it."

![image](https://cloud.githubusercontent.com/assets/12505846/8908312/51ba635c-3473-11e5-874b-c15ce77e6f79.png)

**Comment by jtscott** [comment]
In chrome's advanced settings you need to disable the 'phishing and malware detection". You can check the status of github here, it might be resolved soon if you don't want to disable the option. http://www.google.ca/safebrowsing/diagnostic?site=github.com

**Comment by Kayomani** [comment]
As JT says it should resolve itself in a few days, not much we can do other than wait currently.  Downloading exes from a flagged domain is going to get blocked, fortunately chrome can't scan 7zip files so I've uploaded a copy to the releases page a temp work around.

**Comment by zone117x** [comment]
This issue doesn't appear to be going away. Anyone have any suggestions?

**Comment by zone117x** [comment]
Here is the VirusTotal result for the Jackett installer file. https://www.virustotal.com/en/file/be6b9a0494a0e0a5b430cd4024fc211e9c7399effda8273b5d51e5e5bec7f306/analysis/1438554278/
Perfectly clean. What the hell Chrome?

**Comment by TeRmInAlCrAzY** [comment]
I have just tested this again, with Chrome Version 44.0.2403.125 m, under Windows 10 Home. 

Downloading Jackett.v0.5.1.Windows.Installer.exe, and Jackett.v0.5.1.zip.
.exe passes, .zip fails.

![image](https://cloud.githubusercontent.com/assets/12505846/9028427/5d938832-3970-11e5-9802-1084169dae30.png)

Downloading Jackett.v0.6.0.Windows.Installer.exe or Jackett.Windows.v0.6.0.zip, 
both fail.

![image](https://cloud.githubusercontent.com/assets/12505846/9028449/09a86bd8-3971-11e5-866f-b7dcfe29da0e.png)

**Comment by TeRmInAlCrAzY** [comment]
I don't think that this is Chrome / Google targetting Jackett downloads specifically. I think it is the entire site, Github, that is being flagged. Not sure there is a workaround :(

**Comment by jtscott** [comment]
I downloaded the latest 0.6.0 yesterday with chrome malicious checking turned off just fine. However when I ran the executable on my windows server afterwards it alerted with windows smartscreen.

**Comment by damwthomas** [comment]
This is because Windows smartscreen just doesn't know the program. If it's a program that is flagged as malware or is just unknown to Microsoft you'll get an alert.

**Comment by zone117x** [comment]
Fixed with our new website http://jackett.net
