### ISSUE TITLE
linux compilation not working

### ISSUE THREAD

**Issue by sdesbure** [zone117x/Jackett#117]
Hi, linux compilation using xbuild is not working here's the different issues:

- [x] bakabt.png file doesn't exist but BakaBT.png does (case is important on linux)
- [x] target framework version should be v4.5 (mono doesn't understand v4.5.1 or v4.5.2)
- [ ] Jackett.Tray should be builded only on windows (doesn't work on linux with three errors but works on Windows)

for the 3 I have a "script" to solve them:

```bash
#!/bin/bash
mv src/Jackett/Content/logos/BakaBT.png src/Jackett/Content/logos/bakabt.png
for i in `find . -name '*.csproj'`; do  sed -i -e 's/TargetFrameworkVersion>v4.5.[12]/TargetFrameworkVersion>v4.5/' $i ; done
sed -i -e '/Jackett.Tray/,+1d' src/Jackett.sln
```

My opinion is that the first one should be solved on the repo by renaming it but the two next should be left as is because it works on windows.
We could propose the bash script and update the README.
If you agree, I can do that.

**Comment by Kayomani** [comment]
1 is already fixed on develop.

**Comment by zone117x** [comment]
I agree with getting Jackett to compile on Linux again, we need it for debugging. The Tray program can just be unloaded. And mono should be able to support 4.5.1 which we could probably downgrade to.

**Comment by sdesbure** [comment]
(I took a look in master not develop, my bad...)
mark it as done :)

**Comment by sdesbure** [comment]
downgrading to v4.5.1 is unfoprtunately not sufficient: mono doesn't recognize it and fallback to 2.0 mode.
it need to be v4.5

**Comment by Kayomani** [comment]
Changed the projects to 4.5, no issues in doing so.

Surely you can just unload the tray in what ever you are using for that to be a non issue?

**Comment by sdesbure** [comment]
to unload the tray, I use the shell command shown on top:

```bash
sed -i -e '/Jackett.Tray/,+1d' src/Jackett.sln
```

I took a loohk it seems there's no other solution except this one and having a specific linux.sln (which is kinda what I do)

**Comment by Kayomani** [comment]
#3 is Now fixed.

**Comment by zone117x** [comment]
Jackett.Console and its dependencies can be opened and debugged in MonoDevelop, and built with xbuild. Closing this issue.
