### ISSUE TITLE
Torrentday not working 

### ISSUE THREAD

**Issue by fixxolas** [zone117x/Jackett#121]
Can you please fix this?

It gives error>
 Configuration failed: Input string was not in a correct format.

same on 0.6.0 beta!

**Comment by zone117x** [comment]
@fixxolas We need more information to investigate this. Are you using mono? What version? What system are you using? What language/local is your machine set to?

**Comment by fixxolas** [comment]
Hi,

Using Windows 2012R2, running it natively. 
English language, norwegian locale.

**Comment by zone117x** [comment]
Can you post the exception message from your log? Look in C:\ProgramData\Jackett\log.txt

**Comment by fixxolas** [comment]
2015-08-02 23:42:30.2007 Error Error on 20150802234230 for TorrentDay.txtSystem.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Jackett.Utils.DateTimeUtil.FromTimeAgo(String str) in c:\TeamCity\buildAgent\work\ece2ffdc0168e6f1\src\Jackett\Utils\DateTimeUtil.cs:line 31
   at Jackett.Indexers.TorrentDay.<PerformQuery>d__9.MoveNext() in c:\TeamCity\buildAgent\work\ece2ffdc0168e6f1\src\Jackett\Indexers\TorrentDay.cs:line 94

**Comment by zone117x** [comment]
@fixxolas Can you look in that same log directory and find the TorrentDay parse error file?

**Comment by fixxolas** [comment]
Here's the logfine :-)

http://pastebin.com/SRpGdgGN

**Comment by fixxolas** [comment]
How's the progress. If you need info from torrentday admins/mods etc, let me know.,

**Comment by Kayomani** [comment]
I have applied a fix in a5f97d8ac2e6791b404287a661a0c0579f3100b8 and it now seems to parse if I use your logs but I am not able to test it myself as I am not a member.  I wouldn't mind an invite so I can add full category mapping if there is one going.

**Comment by fixxolas** [comment]
send me your email, you'll have it in a jiffy

**Comment by Kayomani** [comment]
[My name]@gmail.com thanks :+1:

**Comment by fixxolas** [comment]
done

**Comment by Kayomani** [comment]
Confirming the fix works, keep an eye out for the next release.
