### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by bakman2** [zone117x/Jackett#126]
On Synology:

```
08-04 15:55:47 Info Starting Jackett 0.6.0.0
08-04 15:55:47 Info Using HTTP Client: UnixLibCurlWebClient
08-04 15:55:47 Info LibCurl init Ok
08-04 15:55:47 Info LibCurl version libcurl/7.36.0 OpenSSL/1.0.1m zlib/1.2.8 libssh2/1.4.3
08-04 15:55:47 Info Starting web server at http://*:9117/
08-04 15:55:47 Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: /volume1/VARIOUS/Jackett/Content/
```
now when I look at the files they are actually named as: Content\name.ext 
Isn't that a bit strange ?

**Comment by bakman2** [comment]
like this:
![screen shot 2015-08-04 at 18 21 44](https://cloud.githubusercontent.com/assets/333960/9066051/b51a5d7c-3ad5-11e5-8a5f-bc10710fd821.jpg)

**Comment by bakman2** [comment]
I have put the contents from the src in, it starts now the API key remains as "API key"

![screen shot 2015-08-04 at 21 45 33](https://cloud.githubusercontent.com/assets/333960/9070880/4880c83c-3af2-11e5-8b35-fd4e48e1b16b.jpg)

**Comment by Kayomani** [comment]
If you are running from the source make sure you compile as release else it will attempt to use the git source files relative to where visual studio would put them.

public string GetContentFolder()
        {
            // If we are debugging we can use the non copied content.
            string dir = Path.Combine(ApplicationFolder(), "Content"); ;

#if DEBUG
            // When we are running in debug use the source files
            var sourcePath = Path.GetFullPath(Path.Combine(ApplicationFolder(), "..\\..\\..\\Jackett\\Content"));
            if (Directory.Exists(sourcePath))
            {
                dir = sourcePath;
            }
#endif
            return dir;
        }

The api key sounds like a Javascript error, any console errors in the browser? Safari by chance?

**Comment by bakman2** [comment]
The API indeed is caused by, well Jackett, but can be fixed by using Firefox I noticed.

I am not running from source (using mac) - so I downloaded the mono release, but those files seem weird (no folders)

**Comment by Kayomani** [comment]
Sounds like an issue with whatever you used to extract it? extracted it without paths per chance? i have just checked the download and the folders and files are in the correct place inside.

**Comment by sdesbure** [comment]
I have the same issue on linux using bsdtar. Seems that you used a new compressor for the release?
perhaps giving the linux one on .tar.bz2 would be better

**Comment by bakman2** [comment]
I have tried the unzip on commandline, the unarchiver, 7zip, stuff-it, all the same. 
Except for 7zX - that actually gave errors on the files that were in directories. The release file is suspected.

**Comment by zone117x** [comment]
Our new distribution system zips the files using .NET's zip feature. Looks like it may be generating noncompliant zip files. I'll get this fixed for next release. In the mean time we'll try to get the current release repackaged manually.

**Comment by Kayomani** [comment]
I have repacked the mono release to .tar.bz2

**Comment by bakman2** [comment]
Works, thanks!

**Comment by maxcore** [comment]
@bakman2 

How i can install Jackett on synology ? i have install mono , you have a tuto ? am lost

**Comment by bakman2** [comment]
on your syno (in some directory you want to install Jackett):
```
wget https://github.com/zone117x/Jackett/archive/v0.6.4.zip --no-check-certificate
unzip v0.6.4.zip
```
to start Jackett:
```
mono JackettConsole.exe
```
Note that this will not start Jackett in the background.
You will either make a service or use ```screen``` to make it run in the background.
For screen you will need to have your syno bootstrapped and installed it with ```ipkg install screen``` and for ```wget-ssl``` as well (with ssl support)

**Comment by maxcore** [comment]
@bakman2 
i have mistake ...


-ash: mono: not found

when i use : mono JackettConsole.exe

mono is install on my nas , i have forget a step ?

**Comment by Kayomani** [comment]
Mono isn't on your path by the looks of it, try running it using the full path.  You should be able to find mono with "find -iname mono".

**Comment by maxcore** [comment]
find nothing ... i have install mono from the repo of the community

**Comment by bakman2** [comment]
/usr/bin/mono

**Comment by maxcore** [comment]
nothing ... how i can get nothing 
mono is running 
![capture d ecran 2015-09-07 21 11 00](https://cloud.githubusercontent.com/assets/4043787/9724437/1ec947da-55a5-11e5-967b-3a41cef9dd02.png)

**Comment by bakman2** [comment]
Is your Synology up to date ?
Stop/Uninstall the community version of mono.
Install the Synology-mono package.

**Comment by Dr-Bean** [comment]
As was suggested before, SynoCommunity's Mono package isn't put on PATH.
To use our version together with Jackett, add the full path to the executable to start it: `/usr/local/mono/bin/mono /your_Jackett_folder/JackettConsole.exe`.

To use Synology's version, `mono /your_Jackett_folder/JackettConsole.exe` would probably suffice (untested, I don't know which version they are on nowadays). 
Sidenote: Synology's Mono package cannot be used together with SynoCommunity's Sonarr package.

**Comment by bakman2** [comment]
I'm using syno's mono pkg for sonarr

**Comment by Dr-Bean** [comment]
Only if you manually changed stuff to get that going...Which means you might run into problems over time: Synology doesn't necessarily keep their version of the Mono package compatible with Sonarr. We wouldn't have had a separate Mono package if that were the case.
Other than that, go right ahead.
