### ISSUE TITLE
Web UI does not work in Safari on a mac

### ISSUE THREAD

**Issue by kilabyte** [zone117x/Jackett#128]
I just installed Jackett on my mac following the instructions in the git. Everything loads up fine however my dashboard looks like this... and there are no trackers listed on the page?

![screen shot 2015-08-04 at 10 15 18 am](https://cloud.githubusercontent.com/assets/487948/9067341/b96d36ea-3a91-11e5-91b3-57a24f82f661.png)

**Comment by zone117x** [comment]
What browser are you using? Looks like the ajax to fetch data from the API is failing.

**Comment by kilabyte** [comment]
I've tried safari and chrome. should i try firefox?

**Comment by zone117x** [comment]
Open the develop console and find the javascript errors and paste them here

**Comment by kilabyte** [comment]
So it works perfectly in firefox and i was able to get it all up and running. However here is the console from safari...

![screen shot 2015-08-04 at 12 21 11 pm](https://cloud.githubusercontent.com/assets/487948/9070280/8e8ac214-3aa3-11e5-8438-b40101806912.png)

**Comment by Kayomani** [comment]
Apparently Safari isn't a modern browser as it doesn't support Intl:
https://www.npmjs.com/package/handlebars-helper-intl

I have removed this dependency and replaced it with one which should work on Safari.  I can't test this as I don't have access to a Mac so you'll have to let us know if does not work in the next release.

**Comment by whodean** [comment]
Has this been released?

**Comment by Kayomani** [comment]
This was fixed a day ago and the last release was 5 days ago so no.

Releases are typically weekly at the minute but depending on a few things we might not have one this weekend.
