### ISSUE TITLE
[REQ]avistaz.to

### ISSUE THREAD

**Issue by goku93** [zone117x/Jackett#130]

**Comment by Kayomani** [comment]
privatehd.to is already implemented

**Comment by goku93** [comment]
Perfect! thanks :3

**Comment by goku93** [comment]
btw why there isnt a couchpotato host for privatehd?

**Comment by Kayomani** [comment]
Jackett only did TV for Sonarr until last weekend, we have to go over all the existing trackers to add the other categories such as Movies which is used for that end point.

**Comment by Kayomani** [comment]
Added categories for that tracker in fa8d2a3705fa2d344179de6f9ed00a8962f4d6cf

**Comment by goku93** [comment]
Thanks you!

**Comment by Kayomani** [comment]
This is implemented in the next release.
