### ISSUE TITLE
Jackett on ubuntu

### ISSUE THREAD

**Issue by duramato** [zone117x/Jackett#139]
how do i run jackett on ubuntu?

**Comment by zone117x** [comment]
See the installation instructions for Linux in the readme. Let us know if you have any more specific questions or problems.

**Comment by duramato** [comment]
@zone117x  on the readme it says to do  ```mono JackettConsole.exe``` when i perform such command 
```supergonkas@supergonkas:/opt/jackett$ mono JackettConsole.exe
Cannot open assembly 'JackettConsole.exe': Ficheiro ou directoria inexistente```
no such file or dir

**Comment by zone117x** [comment]
Your current directory needs to be the one that contains the JackettConsole.exe file. Do `ls` and it should be one of the listed files.

**Comment by duramato** [comment]
the thing is there isnt one

**Comment by duramato** [comment]
what i did was git clone the github project isnt that way its installed?

**Comment by Kayomani** [comment]
No.

wget https://jackett.net/Download/v0.6.2/Jackett.Mono.v0.6.2.tar.bz2

**Comment by duramato** [comment]
thanks ! its now working fine :)
