### ISSUE TITLE
[REQ] TorrentBytes

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#14]
These are some of the trackers I would like to see supported by jackett. Thanks for your work, jackett is great expansion to sonarr!

**Comment by zone117x** [comment]
Contact me on IRC. I'm not a member of any of those trackers.

**Comment by TRaSH-** [comment]
i'm able to send you a invite for HD-Torrents if needed.

**Comment by zone117x** [comment]
TorrentShack has been added. Need an invite to HD-Torrents and TorrentBytes to add. Message me on IRC.

**Comment by TRaSH-** [comment]
i messaged you on irc, could be a timezone problem between us, but i just need a email address and i'm able to send you a invite for HD-Torrents

**Comment by Ramses26** [comment]
I have invites for HD-Torrents if you still need one. I'd like to see support for HD-Torrents as well.

Thanks

**Comment by damwthomas** [comment]
In a few weeks I'll be on holiday so I'll have to time to work on Jackett. I could probably implement HD-Torrents if I've got an invite.

**Comment by Ramses26** [comment]
If I can get your email, I can send you an invite.

**Comment by damwthomas** [comment]
damwthomas[at]gmail[dot]com

**Comment by Ramses26** [comment]
Invite sent, thanks!

**Comment by TRaSH-** [comment]
@zone117x  has also received a invite from me

**Comment by zone117x** [comment]
I've just merged @damwthomas implementation for HD-Torrents, and confirmed that its working. Compile from latest code to use it, or wait until I put out the next release. I'm removing the HD-Torrent request for this issue's title.

**Comment by Kayomani** [comment]
TorrentBytes is now implemented in develop / available in the next release.

**Comment by nikos8k** [comment]
Hello guys! Could someone of you please send me an invite to hdtorrents here: nikos8kk@gmail.com

thank you so much!
