### ISSUE TITLE
Implementing thetvdb id

### ISSUE THREAD

**Issue by Inrego** [zone117x/Jackett#152]
Hey. I've implemented an indexer, and it's working great. I would like to be able to provide thetvdb id, as described here: https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer#torznab-results

The torrent indexer I am implementing does have thetvdb ID, but not tvrage. TIA

**Comment by Kayomani** [comment]
This has already been done for nxtgn, update your code.  Feel free to send a pull when you are happy with your changes.

**Comment by Inrego** [comment]
Yeah, I'm the one who implemented it in Jackett, and added it to nxtgn. Shortly after I posted here, I decided to do something about it myself.
