### ISSUE TITLE
CP doesn't search on Avistaz

### ISSUE THREAD

**Issue by goku93** [zone117x/Jackett#158]
CP doesn't search for movies that I want on Avistaz. Already tried: Punch Lady, Tomorrow's joe

But in manual search on Jackett they appear ._.

**Comment by Kayomani** [comment]
We pre filter results to ensure they contain the imdb title and the imdb year.

Punch Lady DVDRip XviD-PosTX 

Didn't contain the year so it was skipped so I have changed the code so it allows movies which do not contain a year.

Tomorrow's Joe was also being filtered as the title it was searching for has the apostrophe removed but the result didn't so it wasn't being matched, if there is an apostrophe  its now ignored when matching.

Fix will be in the next release.
