### ISSUE TITLE
Issues connecting to BakaBT tracker

### ISSUE THREAD

**Issue by Viledisgorgement** [zone117x/Jackett#159]
Just wanted to give a thanks to this amazing app. 

I have been having troubles trying to set up my BakaBT account, and I wasn't sure if anyone else was having this problem. When I add and connect my BakaBT credentials, I get the following error.

"Test failed for bakabt: Found no results while trying to browse this tracker"

**Comment by Kayomani** [comment]
Its working here.

Can you try it with logging enabled and post the details ensuring to remove
your user and pass if its not giving you any clues?

**Comment by Viledisgorgement** [comment]
Thanks for the quick response. I changed some settings with my BakaBT profile (show 100 torrents, enable all content) and it seems to be connecting now.
