### ISSUE TITLE
Can't Get Jackett to Work (2 issues)

### ISSUE THREAD

**Issue by viking2** [zone117x/Jackett#161]
I just installed Jacket v0.6.3.0 for Windows, but can't get it to work:

1. When I try to add an indexer (e.g. RARABG or The Pirate Bay)  in Sonarr I get an error in Sonarr.  The log shows:
"Unable to connect to indexer: HTTP request failed: [403:Forbidden] [GET] at [https://thepiratebay.mn/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=0&limit=100]: HTTP request failed: [403:Forbidden] [GET] at [https://thepiratebay.mn/api?t=tvsearch&cat=5030,5040&extended=1&apikey=mki5syujregzychgacewluppykxskwrp&offset=0&limit=100]"

2. If I try to do a manual search in Jackett, e.g. for "Extant", I never get any search results, and Jackett returns: "Your search was done using: None, "

**Comment by Kayomani** [comment]
Looks like either you are your browser (Auto complete?) is changing the url
from the default.  Try adding ensuring you keep the default url i.e. "
https://thepiratebay.mn/
<https://thepiratebay.mn/api?t=tvsearch&cat=5030,5040&extended=1&apikey=>"
perhaps with a different browser.

**Comment by viking2** [comment]
Thank you for your quick response!

However, I am sorry, but I didn't understand. Were you responding to issue #1 or #2? In either case, I am not using a browser URL to add the indexer or do the search.

Also, I don't see how the URL to pirate bay in the log shows that it was changed?

**Comment by Kayomani** [comment]
We'll be doing a setup guide soon™
