### ISSUE TITLE
Password lost. How to reset ?

### ISSUE THREAD

**Issue by spookssi** [zone117x/Jackett#162]
Hi, i push the button save new password but i didnt type a new password.

Im now stuck at the login page of Jackett. Im on a debian 8 server

Can you tell me how to change the password ? (file) I erased /opt/Jackett and reput the files but nothing changed...

Thanks you for your work, i love Jackett with Sonarr :D. Im also french and its very cool to have french tracker on Jackett !

Ps: I'm looking for a invitation for FrenchtorrentDB :dancer: , please invite me ^^ (seedbox and love to share,  Kopymist style :) )

Thx, Have a Nice day. o/

**Comment by Kayomani** [comment]
The config is under ~/.config/Jackett

An empty password should disable the password, perhaps it wasn't completely
empty?

**Comment by spookssi** [comment]
The field wasnt empty, my password was in the field like " ********* " and i press save lol...

I've checked Serverconfig.json and erase the crypted password after a reboot of the Jackett service. The login page asked me again for the pass...

**Comment by Kayomani** [comment]
I can only think the browser has cached the page or the service didn't actually get restarted as doing the above would remove it.

**Comment by Kayomani** [comment]
To reset the config, ensure the service is stopped and delete the config.

rm -R  ~/.config/Jackett
