### ISSUE TITLE
Demonoid Configuration failed

### ISSUE THREAD

**Issue by Strider27** [zone117x/Jackett#165]
A message " Configuration failed: Specified argument was out of the range of valid values. Parameter name: index" Pops up when trying to configure demonoid. Username and PW are correct.

**Comment by Kayomani** [comment]
Are you using a supported version of mono? v4+

**Comment by Strider27** [comment]
Latest version of Jackett, running under Windows Server 2012.

**Comment by Strider27** [comment]
Apologies, not the latest version, since 11 minutes ago. It was installed via the executable, however was using the .zip files prior to the executable (since version 4).

**Comment by Strider27** [comment]
Updating to the next version seems to have solved it.
