### ISSUE TITLE
Can't add immortalseed tracker

### ISSUE THREAD

**Issue by bjorkollur** [zone117x/Jackett#172]
Hi, can some one help me I can't add Immortalseed.
I always get the messages "Configuration failed: Incorrect username or password! tries remaining."

I have verified me login an password 4 times in it is correct.

Any suggestions?

**Comment by Kayomani** [comment]
I just tested it and found no issues.

If you are on mono try making your password alpha numeric, I have heard of issues with special characters before.

**Comment by bjorkollur** [comment]
Strange, my password only includes alpha and numeric characters.
I am running: 
MAC OS X - 10.10.5
Xcode installed
Mono JIT compiler version 4.0.3 ((detached/d6946b4 Wed Jul 29 14:46:23 EDT 2015) 
LibCurl version libcurl/7.43.0 SecureTransport zlib/1.2.5 - (i didn't install any thing, is it installed by default with MAC OS X or did it come with Xcode?   Do I need to install it some other way?) 

When I enter a wrong username or password I get:
 "Configuration failed: Incorrect username or password! [4] tries remaining."

But when I enter right username and password I get:
 "Configuration failed: Incorrect username or password! tries remaining."

Which indicate that something is not working on my site.

**Comment by Kayomani** [comment]
Run the app with the parameters "-l -t" then send me the logs at my name at gmail dot com.  Ensure you strip out your username and password.

**Comment by bjorkollur** [comment]
Here is the log file: https://dl.dropboxusercontent.com/u/57467342/Jackett_Log.txt
I did though change the Password to imortalseeds.

Let me know if there is something else I can do to help,

**Comment by peturm** [comment]
I´m having the same exact issue as the user above (bjorkollur)
adding IS does not work for me, any light on the issue would be really great :)

**Comment by Kayomani** [comment]
Can you curl one of their https pages?

I suspect a certificate issue but I don't have access to a linux machine atm and it works fine for me on Windows.

**Comment by bjorkollur** [comment]
I did run "curl https://immortalseed.me/browse.php"
The result are below, would you like me to run it with any options?

curl https://immortalseed.me/browse.php

	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html lang="en">
		<head>
			<title>immortalseed.me</title>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			<meta http-equiv="refresh" content="2;URL=https://immortalseed.me/login.php?returnto=%2Fbrowse.php" />
			<link rel="stylesheet" type="text/css" href="https://immortalseed.me/style.php?theme=default&style=style.css" />
		</head>
		<body>
			<div style="margin: auto auto; width: 50%; padding-top: 10px;" align="center">
				<table border="0" cellspacing="0" cellpadding="4" class="tborder">
					<tr>
						<td class="thead"><strong><a href="https://immortalseed.me">immortalseed.me</a></strong></td>
					</tr>
					<tr>
						<td class="trow1" align="center"><p>You will now be redirected...</p></td>
					</tr>
					<tr>
						<td class="trow2" align="right"><a href="https://immortalseed.me/login.php?returnto=%2Fbrowse.php" class="smalltext">Click here if you don't want to wait any longer.</a></td>
					</tr>
				</table>
			</div>
		</body>

**Comment by Kayomani** [comment]
Does it work with the new release for you?

**Comment by bjorkollur** [comment]
Yes it does, confirmed working fine. 

Thank You
