### ISSUE TITLE
Showrss use <showrss:rawtitle> instead of <title>

### ISSUE THREAD

**Issue by sammy2142** [zone117x/Jackett#173]
At the moment all sdtv releases get rejected by sonarr as unknown quality.
Showrss cleans up the shows names but also removes the quality information for sdtv shows in the feed.

E.g. 
The Strain S02E10 HDTV x264 BATV becomes
The Strain 2x10 The Assassin in the showrss feed.

The original release name is included in <showrss:rawtitle> tag in the http://showrss.info/feeds/all.rss
rss feed. This problem does not exist for 720p shows.

**Comment by Kayomani** [comment]
Fix available shortly
