### ISSUE TITLE
[REQ] www.bluetigers.ca

### ISSUE THREAD

**Issue by raspdealer** [zone117x/Jackett#174]
Can you add blue tigers in the list ?
Thanks

**Comment by maxcore** [comment]
+1

**Comment by Kayomani** [comment]
Appears to be invite only,.. got one?

**Comment by maxcore** [comment]
@Kayomani  the site closed the invitation today , i will check for you

**Comment by raspdealer** [comment]
After it's 1500 points to get an invitation, I will start grabing points.

**Comment by maxcore** [comment]
Points-Bonus : 12858.1  
@Kayomani give me you email ;) i think i have some bonus :)

**Comment by maxcore** [comment]
@Kayomani i have a invite for you , you want ?
