### ISSUE TITLE
[BUG?] Nxtgen category 4 shows don't show up

### ISSUE THREAD

**Issue by karbowiak** [zone117x/Jackett#178]
Hi there.

I'm trying to utilize Nextgen (Nxtgn) to find a tv show, but said show is only under category 4 it seems (TV/Foreign?), which it seems Jackett doesn't look at.

Example query: http://<jackett>/torznab/nxtgn?apikey=<apikey>&cat=5000,5010,5030,5040&q=Gintberg%20Paa%20Kanten

Which returns nothing.

Any chance of it being enabled so that these tv shows are available via Jackett? :)

Oh and they also switched url, it's not: https://nxgn.org instead

**Comment by Kayomani** [comment]
I think #180 might fix this?

**Comment by karbowiak** [comment]
Ah yes, that might fix it :D

**Comment by Kayomani** [comment]
Merged and a new release available shortly :)
