### ISSUE TITLE
Synology Upstart Script (Step by Step)

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#182]
Per request I'm going to do a walk through for getting jackett automatically starting on synology. 

1. Install Sonarr & Mono 3.10 from synocommunity.
2. Install Mono beta 3.12 from the main Synology repo. (This may or may not be necessary, but I found that I could not get jackett to work without crashing about once a day when I ran it from mono 3.10)
3. Download jackett and place it in /opt/Jackett
4. cd /opt
5. chown -R {user who will run jackett} Jackett
6. Put the following script [jackett.conf](https://gist.github.com/sea3pea0/0e2ebca4a725d98130be) in /etc/init

7. Replace the braces {} in step 5 and in the script with the username that you wish to run Jackett with

8. Like I said, to get jackett working without crashing every day or so I had to install the mono beta package from the main Synology repository. You can attempt to just use mono 3.10 and see if it crashes or not. The script above uses the path for mono beta 3.12 if you want to try using the mono 3.10 package from synocommunity, which needs to be installed for sonarr anyway, then change the exec line in your script to:

      exec /volume1/@appstore/mono/bin/mono --debug JackettConsole.exe

9. From anywhere on command line type "start jackett" . You should see some output telling you that jacket is running and you should be able to browse to {IP Address}:9117 . If not you should check /var/log/upstart/jackett.log and see what that says.

**Comment by maxcore** [comment]
@sea3pea0  THX man you make my day !! :) work great now on my synology :)

**Comment by Kayomani** [comment]
Do you mind if I move this to the readme and include the script in the release?

**Comment by sea3pea0** [comment]
Not at all :)

**Comment by Kayomani** [comment]
Cool

Merged the changes for a release shortly, let me know if I messed anything up.

**Comment by bakman2** [comment]
This does not work for me. 
```/proc/self/fd/9: chdir: line 2: can't cd to /opt/Jackett```

```/opt/Jackett``` does exist and has full (recursive) permissions 
```setuid root``` and not working.

```mono JackettConsole.exe``` within the directory works.

**Comment by alexrengel** [comment]
I'm having the same problem as @bakman2. I'm on a Synology NAS with Synology's Mono Beta v3.12.1-0063 and Synocommunity's Mono Beta v4.0.4.1-5 installed.
