### ISSUE TITLE
Cannot add BeyondHD tracker

### ISSUE THREAD

**Issue by CaptainMoody** [zone117x/Jackett#184]
I have copied and pasted the cookie information for BeyondHD but get an error:

Configuration failed: Invalid cookie header

Not sure if I am copying the correct information or the syntax is incorrect.

Thanks.

**Comment by Kayomani** [comment]
Working fine, what you should copied should look like the following

uid=1000; pass=99864yrd5675675675675fh53y; hashv=5675675675675675675r; member_id=1000

**Comment by CaptainMoody** [comment]
Hi,

Thanks for looking into this.
I entered my cookie information exactly as above (with my uid, pass etc) and still get - Configuration failed: Invalid cookie header.
Not sure what to look for in the log but found this:

2015-09-23 16:05:30.2312 Debug UnixLibCurlWebClient:GetString(Url:https://beyondhd.me/)
2015-09-23 16:05:30.3743 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>

**Comment by chadberg** [comment]
I'm having the same issue, although I noted there is not a member_id parameter in the cookie.

**Comment by chadberg** [comment]
Tried it with SSLFix just to be sure.  No go.

**Comment by CaptainMoody** [comment]
Same here. I have also tried the different --useclients options. No difference.

**Comment by chadberg** [comment]
I've reported it on the BeyondHD forum. I don't think this is a Jackett issue, unless Jackett wants to flag curl to accept invalid certs (and I don't think it should).

**Comment by CaptainMoody** [comment]
It might be worth adding the jackett error to your post on BeyondHD. I know there are other people with the same problem from IRQ chats and they might not put two and two together.

**Comment by Kayomani** [comment]
If you pull https://beyondhd.me with curl from your command line does it work?  It didn't on my ubuntu system, complained about certificates.

**Comment by chadberg** [comment]
That what I reported, that it isn't Jackett, it's curl unable to connect because of the cert issue.

**Comment by SevenNine** [comment]
This has been corrected by the admins.  Now working.
