### ISSUE TITLE
T411 needs to use RSS for non query searches

### ISSUE THREAD

**Issue by raspdealer** [zone117x/Jackett#199]
Hi,

Now I understand why I never grabbed links automatically...
I just opened the feed request : 
15-10-2 20:48:08.6|Debug|Torznab|Downloading Feed http://192.168.1.116:9117/torznab/t411/api?t=tvsearch&cat=5040,5070&extended=1&apikey=<removed>&offset=0&limit=100

And it's only one element : la-ferme-en-folie-2006-1080p-hdtv-dd5-1-x264-ill-mkv-up-sebfunix
A 5 years old torrent... Why ?

**Comment by Kayomani** [comment]
The indexer is using their API, having just looked at the docs it only supports searching and not getting the latest results.

**Comment by raspdealer** [comment]
But if I remove the cat parameter, I can get more results...

**Comment by raspdealer** [comment]
Ok but these results are ALWAYS the same... and my single result is inside...
So there is definitively no way to use rss with t411?

**Comment by Kayomani** [comment]
It searches for an space where there is no text and that is just what gets returned.  Perhaps it might be more sensible to just return the top 100 for the day when there is no query string?

**Comment by raspdealer** [comment]
Yes with the specified categories... Would be nice.
It is possible to do that ?

**Comment by Kayomani** [comment]
The rss could be used as a get latest feed.  It does not matter that its not a direct link as Jackett can cope with navigating between pages when a torrent file is requested.

I don't really have time to rewrite for a bit

**Comment by raspdealer** [comment]
Ok but the RSS support for T411 would be nice.
May be we need to rename this issue.
Is it hard to do ? How can I help you ?

**Comment by Kayomani** [comment]
If you can't make the changes one of the things which would be really nice is a list of categories

For example
<category domain="https://www.t411.in/torrents/search/?subcat=246">Windows</category>

If you could do me a list of the categories that would be great, I need the results in the format:

AddCategoryMapping("246", TorznabCatType.PC);

See for the available categories
https://github.com/zone117x/Jackett/blob/master/src/Jackett/Models/TorznabCatType.generated.cs

See this for an example usage:
https://github.com/zone117x/Jackett/blob/master/src/Jackett/Indexers/HDTorrents.cs

**Comment by raspdealer** [comment]
`AddCategoryMapping("624", TorznabCatType.Console);
AddCategoryMapping("307", TorznabCatType.ConsoleNDS);
AddCategoryMapping("308", TorznabCatType.ConsolePSP);
AddCategoryMapping("307", TorznabCatType.ConsoleWii);
AddCategoryMapping("309", TorznabCatType.ConsoleXbox);
AddCategoryMapping("309", TorznabCatType.ConsoleXbox360);
AddCategoryMapping("307", TorznabCatType.ConsoleWiiwareVC);
AddCategoryMapping("309", TorznabCatType.ConsoleXBOX360DLC);
AddCategoryMapping("308", TorznabCatType.ConsolePS3);
AddCategoryMapping("239", TorznabCatType.ConsoleOther);
AddCategoryMapping("245", TorznabCatType.ConsoleOther);
AddCategoryMapping("246", TorznabCatType.ConsoleOther);
AddCategoryMapping("626", TorznabCatType.ConsoleOther);
AddCategoryMapping("628", TorznabCatType.ConsoleOther);
AddCategoryMapping("630", TorznabCatType.ConsoleOther);
AddCategoryMapping("307", TorznabCatType.Console3DS);
AddCategoryMapping("308", TorznabCatType.ConsolePSVita);
AddCategoryMapping("307", TorznabCatType.ConsoleWiiU);
AddCategoryMapping("309", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("308", TorznabCatType.ConsolePS4);
AddCategoryMapping("631", TorznabCatType.Movies);
AddCategoryMapping("631", TorznabCatType.MoviesForeign);
AddCategoryMapping("455", TorznabCatType.MoviesOther);
AddCategoryMapping("633", TorznabCatType.MoviesOther);
AddCategoryMapping("631", TorznabCatType.MoviesSD);
AddCategoryMapping("631", TorznabCatType.MoviesHD);
AddCategoryMapping("631", TorznabCatType.Movies3D);
AddCategoryMapping("631", TorznabCatType.MoviesBluRay);
AddCategoryMapping("631", TorznabCatType.MoviesDVD);
AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("395", TorznabCatType.Audio);
AddCategoryMapping("623", TorznabCatType.AudioMP3);
AddCategoryMapping("400", TorznabCatType.AudioVideo);
AddCategoryMapping("402", TorznabCatType.AudioVideo);
AddCategoryMapping("405", TorznabCatType.AudioAudiobook);
//AddCategoryMapping("1", TorznabCatType.AudioLossless);
AddCategoryMapping("403", TorznabCatType.AudioOther);
AddCategoryMapping("642", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
AddCategoryMapping("233", TorznabCatType.PC);
AddCategoryMapping("236", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
//AddCategoryMapping("1", TorznabCatType.PCISO);
AddCategoryMapping("235", TorznabCatType.PCMac);
AddCategoryMapping("627", TorznabCatType.PCPhoneOther);
AddCategoryMapping("246", TorznabCatType.PCGames);
AddCategoryMapping("625", TorznabCatType.PCPhoneIOS);
AddCategoryMapping("625", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("639", TorznabCatType.TV);
AddCategoryMapping("433", TorznabCatType.TV);
AddCategoryMapping("639", TorznabCatType.TVWEBDL);
AddCategoryMapping("433", TorznabCatType.TVWEBDL);
AddCategoryMapping("639", TorznabCatType.TVFOREIGN);
AddCategoryMapping("433", TorznabCatType.TVFOREIGN);
AddCategoryMapping("639", TorznabCatType.TVSD);
AddCategoryMapping("433", TorznabCatType.TVSD);
AddCategoryMapping("639", TorznabCatType.TVHD);
AddCategoryMapping("433", TorznabCatType.TVHD);
AddCategoryMapping("635", TorznabCatType.TVOTHER);
AddCategoryMapping("636", TorznabCatType.TVSport);
AddCategoryMapping("637", TorznabCatType.TVAnime);
AddCategoryMapping("634", TorznabCatType.TVDocumentary);
//AddCategoryMapping("1", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
AddCategoryMapping("340", TorznabCatType.Other);
AddCategoryMapping("342", TorznabCatType.Other);
AddCategoryMapping("344", TorznabCatType.Other);
AddCategoryMapping("391", TorznabCatType.Other);
AddCategoryMapping("392", TorznabCatType.Other);
AddCategoryMapping("393", TorznabCatType.Other);
AddCategoryMapping("394", TorznabCatType.Other);
AddCategoryMapping("234", TorznabCatType.Other);
AddCategoryMapping("638", TorznabCatType.Other);
AddCategoryMapping("629", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
AddCategoryMapping("408", TorznabCatType.Books);
AddCategoryMapping("404", TorznabCatType.BooksEbook);
AddCategoryMapping("406", TorznabCatType.BooksComics);
AddCategoryMapping("407", TorznabCatType.BooksComics);
AddCategoryMapping("409", TorznabCatType.BooksComics);
AddCategoryMapping("410", TorznabCatType.BooksMagazines);
//AddCategoryMapping("1", TorznabCatType.BooksTechnical);
//AddCategoryMapping("1", TorznabCatType.BooksOther);
//AddCategoryMapping("1", TorznabCatType.BooksForeign);`
