### ISSUE TITLE
Sonarr not filtering search results TorrentDay

### ISSUE THREAD

**Issue by FSurani** [zone117x/Jackett#200]
I added TorrentDay as per the instructions, testing to ensure it's working correctly and it is. I can do a manual search from the Jackett webui and it's working, but in Sonarr, after adding it (and also testing) when I try to do a manual search, the items from TorrentDay are not filtered based on the episode. I seem to get random results. 

Basically doesn't seem like the "Search" feature is working

**Comment by Kayomani** [comment]
Have you disabled use rage id?

**Comment by FSurani** [comment]
No I didn't... and that fixed the problem!! <3 ty
