### ISSUE TITLE
Bug in adding bitmetv

### ISSUE THREAD

**Issue by poplolnman** [zone117x/Jackett#203]
Configuration failed: Found no results while trying to browse this tracker

Oct 04, 2015 02:52:21 AM Error Exception in Configure
 
Oct 04, 2015 02:52:21 AM Info Found 0 releases from BitMeTV
 
Oct 04, 2015 02:51:03 AM Error Exception in Configure
 
Oct 04, 2015 02:51:03 AM Info Found 0 releases from BitMeTV
 
Oct 04, 2015 02:50:29 AM Error Exception in Configure
 
Oct 04, 2015 02:50:29 AM Info Found 0 releases from BitMeTV
 
Oct 04, 2015 02:49:59 AM Error Exception in test_indexer
 
Oct 04, 2015 02:49:59 AM Info Found 0 releases from BitMeTV
 
Oct 04, 2015 02:46:34 AM Info Starting web server at http://*:9117/
 
Oct 04, 2015 02:46:34 AM Info LibCurl version libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
 
Oct 04, 2015 02:46:34 AM Info LibCurl init Ok
 
Oct 04, 2015 02:46:34 AM Info Using HTTP Client: UnixLibCurlWebClient
 
Oct 04, 2015 02:46:34 AM Info Starting Jackett 0.6.7.0

**Comment by poplolnman** [comment]
getting the same for bakabt...


When

Level

Message


Oct 04, 2015 05:24:51 AM Error Exception in Configure
 
Oct 04, 2015 05:24:51 AM Info Found 0 releases from BakaBT
 
Oct 04, 2015 05:24:13 AM Error Exception in Configure
 
Oct 04, 2015 05:24:13 AM Info Found 0 releases from BakaBT
 
Oct 04, 2015 05:23:52 AM Error Exception in Configure
 
Oct 04, 2015 05:23:52 AM Info Found 0 releases from BakaBT

**Comment by poplolnman** [comment]
sorry but also getting the same thing for animetorrents.me, when that worked yesterday...

**Comment by poplolnman** [comment]
in jackett's test, it passes, but when i test it with sonarr, sonarr cant connect to it...

**Comment by Kayomani** [comment]
Fixed
