### ISSUE TITLE
Torrentleech error

### ISSUE THREAD

**Issue by subzero79** [zone117x/Jackett#209]
Something changed on TL. This is the error

http://pastebin.com/SPg4mZQK

This is mono version 

Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

Jackett is version 0.6.7.0 running inside a docker container. This one https://hub.docker.com/r/dreamcat4/jackett/

**Comment by Kayomani** [comment]
They've gone https only
