### ISSUE TITLE
t411 error : Unexpected character...

### ISSUE THREAD

**Issue by ErwanNumb** [zone117x/Jackett#210]
Hi,

When I try to test or update t411 config, I got the following error :
Test failed for t411: Unexpected character encountered while parsing value: <. Path '', line 0, position 0

Do you know what's going on? It was working perfectly some days ago...

Thanks!

**Comment by ErwanNumb** [comment]
Ok it was the older version without domain name changed.

It fully works with 0.6.7!

**Comment by raspdealer** [comment]
Can you make the rss working?
