### ISSUE TITLE
How to update easily

### ISSUE THREAD

**Issue by raspdealer** [zone117x/Jackett#217]
Just looking for a way to easily update to the last release version on linux raspberry.
Any suggestion or script ?

**Comment by raspdealer** [comment]
Here is my current script. But I need to change manually the version number...

>sudo rm -rf Jackett.Mono*
>sudo rm -rf Jackett
>wget http://jackett.net/Download/v0.6.8/Jackett.Mono.v0.6.8.tar.bz2
>tar -xvf Jackett.Mono*
>sudo rm -rf /opt/Jackett/
>sudo mkdir /opt/Jackett
>sudo mv Jackett/* /opt/Jackett
>sudo chown -R osmc:osmc /opt/Jackett
>sudo reboot

**Comment by RXWatcher1** [comment]
how about this..it scrapes the download page to pull the latest version and if its different than the installed version, it installs it.

if [ ! -f version.txt ]; then
echo 'v0.0.0' > version.txt
fi
CVERSION=$(cat version.txt)
WVERSION=$(curl -s https://jackett.net/Download| grep -m 1 -o 'v[0-9.].[0-9.][0-9.]*[\ \t]*'|head -n 1)
if [ $WVERSION != $CVERSION ]
then
rm -rf Jackett.Mono*.bz2
wget https://jackett.net/Download/${WVERSION}/Jackett.Mono.${WVERSION}.tar.bz2 
kill -9 `screen -ls | grep jackett | awk '{print $1}' | cut -d. -f 1`
tar -xf Jackett.Mono*
echo $WVERSION > version.txt
# cd Jackett
screen -d -m -S jackett mono Jackett/JackettConsole.exe
screen -wipe
fi

**Comment by raspdealer** [comment]
what does that mean ?
kill -9 `screen -ls | grep jackett | awk '{print $1}' | cut -d. -f 1`
screen -d -m -S jackett mono Jackett/JackettConsole.exe
screen -wipe

**Comment by RXWatcher1** [comment]
I run mine in screen. One kills my existing screen session.  One creates my
new screen session and the 3rd cleans it up.  Perhaps you should Google
Linux screen.

**Comment by raspdealer** [comment]
I use it headless with remote access.
Here is my final one.

if [ ! -f cur-jackett.txt ]; then
echo 'v0.0.0' > cur-jackett.txt
fi
CVERSION=$(cat cur-jackett.txt)
WVERSION=$(curl -s https://jackett.net/Download| grep -m 1 -o 'v[0-9.].[0-9.][0-9.]*[\ \t]*'|head -n 1)
if [ $WVERSION != $CVERSION ]
then
sudo rm -rf Jackett.Mono*.bz2
sudo rm -rf Jackett
wget https://jackett.net/Download/${WVERSION}/Jackett.Mono.${WVERSION}.tar.bz2 
tar -xf Jackett.Mono*
echo $WVERSION > cur-jackett.txt
fi
sudo rm -rf /opt/Jackett/
sudo mkdir /opt/Jackett
sudo mv Jackett/* /opt/Jackett
sudo chown -R osmc:osmc /opt/Jackett
sudo reboot

**Comment by raspdealer** [comment]
updated
