### ISSUE TITLE
morethan.tv Configuration Failed:

### ISSUE THREAD

**Issue by hxcadam** [zone117x/Jackett#223]
Doesn't give me an error.  I tried using a bad password and it gave me incorrect password error.  I'm on Windows 10 using latest release.

**Comment by nphil** [comment]
I'm having the same issue, cannot add morethan.tv, keeps saying config failed. On ubuntu 15 headless with mono 4.0.

**Comment by hxcadam** [comment]
Fixed in 0.6.9  Thanks for all your work!!!
