### ISSUE TITLE
[REQ] Beyondhd.me

### ISSUE THREAD

**Issue by EasyMoney123** [zone117x/Jackett#23]
Please add support for these trackers when you get the chance.

Thanks

**Comment by rarbg** [comment]
@zone117x 
https://rarbg.com/pubapi/apidocs.txt
API docs if needed

**Comment by zone117x** [comment]
@rarbg Oh nice to see there is an API! I'll get it implemented. Are you a rep for rarbg? 

And @EasyMoney123 I'll get beyondhd added as well.

**Comment by rarbg** [comment]
@zone117x yes i am :)

**Comment by EasyMoney123** [comment]
Thanks @zone117x

**Comment by zone117x** [comment]
@rarbg I've added support for rarbg but the API is lacking. No publish date, no seeders/leechers, no torrent size, no url to the show rarbg.com torrent page. It *barely* works with Sonarr. Let me know if you get those added to the API and I'll update.

**Comment by rarbg** [comment]
@zone117x 
No idea that Sonarr wanted those. Ill extend the api later today and update the api docs and post here when im done. It will be just an extra parameter in the url.

**Comment by rarbg** [comment]
@zone117x 
Sorry for the delay.
Please use json_extended as value for the format parameter in the api.
This will return you seeders,leechers,size and up date in the api.
Unfortunately i cant link to the url on our page due to legal reasons

**Comment by d2dyno** [comment]
@rarbg Thanks for the tip!

@zone117x I've submitted another commit for the Rarbg.cs file. Please merge it (includes update to site address, rarbg.to now, as well as aforementioned json_extended changes).

**Comment by zone117x** [comment]
@d2dyno You need to use the new info (seeders, leechers, size) in the PerformQuery method otherwise they won't be set. If you add those and do a pull request I'll merge it in.

**Comment by d2dyno** [comment]
@zone117x unfortunately my knowledge stops after simple edits. Unless this is a case where I can pull from other examples (ie thepiratebay), and splice in that code? To do it cleanly, you may want to do it, as there's no guarantees of that here. I'd be happy to learn though.

**Comment by zone117x** [comment]
@d2dyno Thanks for the attempt but looks like I'll need to do it :p

**Comment by d2dyno** [comment]
@zone117x Ok, my apologies. I'll see how you do it, and learn from that :)

**Comment by zone117x** [comment]
BeyondHD has been implemented.
