### ISSUE TITLE
Can't add any trackers

### ISSUE THREAD

**Issue by laxstar18** [zone117x/Jackett#239]
I have tried adding 3 different trackers that I have accounts with and each one gives me this error  "Configuration failed: Data protection failed." Not sure what is going on. Oh and I'm running it via a docker using the arch build. Any help would be greatly appreciated.

Thanks

**Comment by raspdealer** [comment]
The main project is in hibernation for now...
This fork is active : https://github.com/Jackett/Jackett
@laxstar18 Can you reopen your issue on the fork and close this one?
