### ISSUE TITLE
Release.v0.2.5.zip - not able to add MoreThan or TPB

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#24]
Update: I was able to get the latest release working with mono. I renamed the config folder: /usr/share/Jackett to something different.
Then I created a new one and chown to the user that I run Jackett with. If you have the same problem as me you probably could just remove and readd the indexers but I didn't try that. 

I still am not able to add morethan or tpb. I installed libcurl-dev but this is what happens when I try to add the indexers:
![image](https://cloud.githubusercontent.com/assets/5307776/7378047/5ac058f0-ed86-11e4-82d9-cb87d8889a75.png)

**Comment by sea3pea0** [comment]
here's some logs https://gist.github.com/sea3pea0/70d633fa1e080fb109bb with some errors showing up.

**Comment by sea3pea0** [comment]
I was thinking this might be due that I am running jackett on a synology with optware. Libcurl-dev is installed by ipkg under /opt. Anybody with a synology able to get these 2 trackers to work with jackett?

**Comment by zone117x** [comment]
Closing this since we have the other issue open for libcurl
