### ISSUE TITLE
[REQ] New Tracker - Blu-Evolution

### ISSUE THREAD

**Issue by sider1681** [zone117x/Jackett#242]
I'd like to request the indexer http://blu-evolution.org/ be added for Couchpoato. They've got great HD content that doesn't always make it to the other indexers.

**Comment by raspdealer** [comment]
I think this project is in hibernation...
This fork will be active for now : https://github.com/Jackett/Jackett

**Comment by raspdealer** [comment]
The main project is in hibernation for now...
This fork is active : https://github.com/Jackett/Jackett
@sider1681 Can you reopen your issue on the fork and close this one?
