### ISSUE TITLE
request: debug features

### ISSUE THREAD

**Issue by aroundmyroom** [zone117x/Jackett#28]
I was able to add iptorrents, morethantv but it keeps failing on bitmetv

I have this error, but that is only one part, a 2nd one is that my torrents seems to get corrupted and therefore a found torrent will never start .. but I cannot find out how to debug that from Jackett (is there a log functionality?)

15-5-1 19:56:45.8|Debug|Torznab|Downloading Feed http://usenix.local:9117/api/bitmetv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=&offset=0&limit=100
15-5-1 19:56:45.8|Trace|HttpClient|Req: [GET] http://usenix.local:9117/api/bitmetv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=&offset=0&limit=100
15-5-1 19:56:48.2|Trace|HttpClient|Res: [GET] http://usenix.local:9117/api/bitmetv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=&offset=0&limit=100 : 200.OK (2,453 ms)
15-5-1 19:56:48.2|Warn|Torznab|Unable to connect to indexer: Text node cannot appear in this state. Line 1, position 1.

System.Xml.XmlException: Text node cannot appear in this state. Line 1, position 1.

any idea (from Jackett I can successfully connect)

NB Running under Debian / Linux

**Comment by zone117x** [comment]
Result parsing errors are now stored in error files next to the log file. It contains the exception stack trace and the html page it errored on. Should make debugging a lot easier.
