### ISSUE TITLE
Morethan.tv and iptorrents not working on 2.6

### ISSUE THREAD

**Issue by nytemyst** [zone117x/Jackett#31]
These worked for me in 2.4 but don't seem to work in 2.6
Using a windows server 2008 r2 as the box.

Testing iptorrents returns back Found no result while trying to browse this tracker.
Morethantv returns unexpected character encountered while parsing value: < path ", line 0 , position 0.

**Comment by M0UL** [comment]
i have the same problem, see my log post

**Comment by zone117x** [comment]
Look for a morethantv or iptorrents error file next to the log and paste them. I need to see the results page for whatever you were searching/browsing that is causing the error.

**Comment by aroundmyroom** [comment]
I just tested iptorrents and morethantv, my issue was that Sonarr did something wrong in a previous dev. version of my: above did not work as the torrents were seen as nzb files .. checking sonar it showed me it saved torznab as newznab causing it not to work. Removing the entries re-adding it and I am now downloading a missed episode of 2 broke girls without issue through Jackett and iptorrents

But .. I have another issue .. with bitmetv ;-)

**Comment by zone117x** [comment]
This should be fixed now.
