### ISSUE TITLE
[Bug] download path for piratebay missing a /

### ISSUE THREAD

**Issue by g10rgio** [zone117x/Jackett#33]
Not sure if its my setup but piratebay links have a missing / in the path to the download for the torrent, example:

https://thepiratebay.setorrent/11875665/VICE.S03E08.SDTV.[2Maverick].mp4

You can see this link if you hover your mouse of the over the release title in sonarr.

**Comment by zone117x** [comment]
Nice find, fixed in latest code. Will be fixed in next release.
