### ISSUE TITLE
Linux upstart script

### ISSUE THREAD

**Issue by McGriddle** [zone117x/Jackett#35]
Figured I'd share this for anyone that's also running on linux.

Here is an upstart script for Jackett.

```
author "Simon Tallmyr - Nosscire"
description "Upstart Script to run NzbDrone as a service on Ubuntu/Debian based systems, as well as others"

#Set username for the process. Should probably be what you use for logging in
setuid mcg
setgid mcg

#This is the install directory. If you installed using a deb package or the NzbDrone Repository you do not need to change this
env DIR=/opt/Jackett

start on runlevel [2345]
stop on runlevel [016]

#respawn
script
    chdir $DIR
    exec mono Jackett.exe
end script
```

A few things I had to do:
 - ensure /opt/Jackett had all the files from a release in it
 - ensure that /opt/Jackett was owned by mcg:mcg
 - ensure /usr/share/Jackett was owned by mcg:mcg

**Comment by conihorse** [comment]
My ubuntu 14.04 didn't have chdir as standard, so went with the below tweak which works fine.
..
#respawn
script
    exec mono $DIR/Jackett.exe
end script

**Comment by sea3pea0** [comment]
Thanks for sharing this. So you haven't had any problems running Jackett as non-root? Initially I was using setuid to run jackett as a user other than root but was having problems until I changed to root.

**Comment by zone117x** [comment]
Posted in wiki https://github.com/zone117x/Jackett/wiki/Linux-upstart-script
