### ISSUE TITLE
systemd script for Jackett

### ISSUE THREAD

**Issue by delphiactual** [zone117x/Jackett#36]
[Unit]
Description=Jackett Daemon
After=network.target

[Service]
User=[user]
Restart=always
RestartSec=5
Type=simple
ExecStart=/usr/bin/mono --debug /opt/Jackett/Jackett.exe
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target

**Comment by ctlaltdefeat** [comment]
Nice :+1:

**Comment by zone117x** [comment]
Posted in wiki https://github.com/zone117x/Jackett/wiki/Systemd-script

**Comment by raspdealer** [comment]
Jackett.exe doesn't exist anymore ?

**Comment by Kayomani** [comment]
Its Jackett.console.exe

**Comment by raspdealer** [comment]
Yes I found that. Thanks for editing the file ;-)
