### ISSUE TITLE
Headless Linux exception on v0.2.6 (reoccurance of issue #6)

### ISSUE THREAD

**Issue by conihorse** [zone117x/Jackett#37]
https://github.com/zone117x/Jackett/issues/6

Suggest reopening this issue - see comments within.

**Comment by conihorse** [comment]
It seems this is configuration/permissions related because after starting jackett as root, it successfully starts, and then subsequently running as non-root user is successful every time.

**Comment by zone117x** [comment]
The latest code will not require root privileges.
