### ISSUE TITLE
Test failed for SITENAME Unknown char

### ISSUE THREAD

**Issue by SuperKingZ** [zone117x/Jackett#38]
Getting this error on Ubuntu 15.04 with all the newest updates.
After configuring Sonarr.  I entered a torrent website and get a error when testing it
Test failed for IPTorrents/Torrentleech Unknown char
I think this happen after login because I get a message that say so many tries left if the login is wrong

System : Ubuntu 15.04
Mono JIT compiler version 3.10.0 (tarball Wed Nov  5 12:50:04 UTC 2014)

**Comment by SuperKingZ** [comment]
Ok after updating Mono I get the following error on adding torrent websites
Configuration failed: Error getting response stream (ReadDone1): ReceiveFailure
Mono JIT compiler version 4.0.1 (tarball Tue Apr 28 11:47:58 UTC 2015)

**Comment by SuperKingZ** [comment]
The problem is Ubuntu specific.  Install mono and Jackett on Arch Linux and no problems

**Comment by blkphnx** [comment]
I had the same error in Ubuntu and OS X with Mono 4.0.1. I downgraded to Mono JIT compiler version 3.12.1. I dont see the issue anymore. Looks like a bug introduced in recent version of Mono.

Not sure if its same bug as below but looks similiar
https://bugzilla.xamarin.com/show_bug.cgi?id=14656

**Comment by zone117x** [comment]
Closing this as it doesn't appear to be a Jackett problem.
