### ISSUE TITLE
Torrent Leech & Torrent Shack errors

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#41]
torrent leech: https://gist.github.com/sea3pea0/4efed0cb5a0b0c95b71c

torrent shack: https://gist.github.com/sea3pea0/4efed0cb5a0b0c95b71c

**Comment by zone117x** [comment]
You're a good error reporter :) These ones should be fixed in latest code but not last release. I'll check to make sure for next release. You may want to try building and running latest code.

**Comment by zone117x** [comment]
I believe these are fixed now.
