### ISSUE TITLE
[REQ] T411

### ISSUE THREAD

**Issue by eyotiste** [zone117x/Jackett#42]
Hello,
T411 is a big semi-private french tracker.
Is-it possible to add-it ?

I tried by myself but this kind of thing are too far for me now :(

Here is the api url : http://api.t411.io/

Thanks you in advance and sorry for my poor english :'(

**Comment by manuliege** [comment]
+1

**Comment by ErwanNumb** [comment]
+1 very nice tracker

**Comment by ErwanNumb** [comment]
Any progress on that ? :/

**Comment by ErwanNumb** [comment]
I've started writing the module based on Strike & Alpharatio, but still have some parsing errors (I actually don't really know why, definetly not an expert of C#...).
http://pastebin.com/EiAX5a8k

**Comment by KiLMaN** [comment]
Hi,
I've written a little nodejs proxy that translate Torznab to T411 api
You can find it here : https://github.com/KiLMaN/T411-Torznab
I will continue to add more and more features in the future

**Comment by eyotiste** [comment]
@KiLMaN Works fine (after I pluged my brain)

**Comment by zone117x** [comment]
T411 has been implemented.
