### ISSUE TITLE
Rarbg issues

### ISSUE THREAD

**Issue by d2dyno** [zone117x/Jackett#45]
The Rarbg indexer has some issues:

-Search not properly functioning: lists episodes other than what was searched for.
-Seeders/Leechers not functional (shows 1/0 on every episode)
-Size is displayed as 0 for every listing.
-Site should point to rarbg.to, not rarbg.com (Pushed commit for this)

Rarbg is my absolute favorite torrent site, thus why I'm so PUMPED to get this working :)

**Comment by zone117x** [comment]
Those features are missing from the rargb API, ask @rargb to get them implemented. 
https://github.com/zone117x/Jackett/issues/23

**Comment by zone117x** [comment]
This indexer is now directly supported in Sonarr's dev branch so it will be deprecated in Jackett.
