### ISSUE TITLE
Strike .torrent support

### ISSUE THREAD

**Issue by xcpep** [zone117x/Jackett#52]
Hey, people who use Blackhole in Sonarr for torrents are unable to use indexers such as Strike and ThePirateBay.

ThePirateBay is understandable since they only provide a magnet link.
Strike could be fixed since they allow torrent and magnet links.

The .torrent from Strike can't be downloaded because they haven't implemented it into their API, however this can be bypassed by redirecting users to: http://getstrike.net/torrents/api/download/{INFO_HASH}.torrent

**Comment by zone117x** [comment]
Fixed.
