### ISSUE TITLE
[REQ] HDBits (hdbits.org)

### ISSUE THREAD

**Issue by Enf0** [zone117x/Jackett#53]
Would really love support for this tracker.

https://hdbits.org/api/

Contact me if you need anything.

**Comment by zone117x** [comment]
I'd like to add the tracker but I'm not a member of that one. Can you contact me on IRC/skype/email?

**Comment by zone117x** [comment]
Actually HDBits has a good API so it can be integrated directly into Sonarr. There  is already a pull request: https://github.com/Sonarr/Sonarr/pull/235
I did what I can to move it along for merge.
