### ISSUE TITLE
[IPTorrents] Configuration Failed

### ISSUE THREAD

**Issue by Mirabis** [zone117x/Jackett#54]
Hi,

I'm unable to add my IPTorrents account to Jackett :( PirateBay etc works fine.

It Says: " Configuration failed:" with no info after: 

Any idea?

**Comment by zone117x** [comment]
Not sure why you're getting this. Possibly you're using the wrong credentials. I've just tested IPTorrents and it works fine.

**Comment by Mirabis** [comment]
I've copy pasted , re-done it , re-logged. Logging in to the site works fine, adding to the configuration does not.

Any characters not supported in the Jackett config?

**Comment by Mirabis** [comment]
Forked the Repo, ran it on windows = Works fine.
Run the same release on Debian = Config error.

Must be something with locales or the OS

**Comment by zone117x** [comment]
I have IPT setup on ubuntu without issue. What kind of characters are in use that you think may not be supported?

**Comment by Mirabis** [comment]
I used `i8#uPAy%7trr` as password ( dw changed already).

But same password works fine on Windows, so somehow it won't work when i run it on Debian.

**Comment by zone117x** [comment]
@Mirabis I'll do some research to see if mono fucks up the escaping. Wouldn't be surprised if that was the issue.
