### ISSUE TITLE
[REQ] nCore.cc 

### ISSUE THREAD

**Issue by gurabli** [zone117x/Jackett#60]
Would be great if you could add support for ncore.cc site. 

It is a great site and the largest one in my country with largest userbase and excellent seed availability. 
If I'm correct, they do not have an API, but there is a plugin for CooucPotato that adds search for movies and it is working great, perhaps this would be of help to you.
https://github.com/gala132/nCoreCouchPotatoProvider

I can do the testing (running Ubuntu Server Trusty) if needed!

**Comment by gurabli** [comment]
Any ideas if this would be possible?

**Comment by damwthomas** [comment]
We cannot add this if we don't have access to the website.

**Comment by zone117x** [comment]
Yeah I'm not a member of this one either. If you have an invite you should send it to @damwthomas

**Comment by gurabli** [comment]
Excellent, I'm very glad you will add this, I'm here to test and give you support! I have an invite, to which e-mail address should I send it?
Once again, thanks for adding this, it is really a great site!

**Comment by damwthomas** [comment]
myusername@gmail.com

**Comment by gurabli** [comment]
@damwthomas Thanks, I have just sent you an invite! Let me know if you have received it and if you need any help with the site! My email is also my username @gmail.com
Very much looking forward to try this out!

**Comment by gurabli** [comment]
@damwthomas I have also sent an email with some translation help, just to be sure.

**Comment by zone117x** [comment]
@gurabli Do you have another invite to nCore? @damwthomas is running into some problems trying to implement the tracker https://github.com/zone117x/Jackett/pull/124

**Comment by gurabli** [comment]
@zone117x Sure, just send me an email address and I'm sending the invite.

**Comment by zone117x** [comment]
My username at gmail.com

**Comment by gurabli** [comment]
Invite sent! 
Is the site is in Hungarian (although very similar layout as many other sites) I have created some screenshots for damwthomas with English translations added. Should I send these to you, might be of help?

**Comment by zone117x** [comment]
nCore is now implemented in develop, will be available next release.
