### ISSUE TITLE
[REQ] add PrivateHD (formerly PublicHD) support

### ISSUE THREAD

**Issue by stewsta** [zone117x/Jackett#61]
https://privatehd.to/

Currently open registration

**Comment by zone117x** [comment]
After evaluating this tracker, it doesn't look possible to implement in its current state. Show episodes cannot be directly searched for and displayed on their website. 
You can petition their staff to either implement an API, or create a more bot-friendly website.

**Comment by TRaSH-** [comment]
they are working on a "RSS download list (so that you auto download on your client or seedbox)",
don't know if that will work when it's done with there tracker

**Comment by zone117x** [comment]
Ask them to implement a JSON search endpoint like /torrents.php?search=game+of+thrones+s01e1&output=json
And the login cookie or an API key for security. Its really not hard to implement.

**Comment by zone117x** [comment]
Looks like the site supports episode search now and can be implemented. Reopening.

**Comment by zone117x** [comment]
Implemented.
