### ISSUE TITLE
Modify Existing Indexer

### ISSUE THREAD

**Issue by mitchmiller** [zone117x/Jackett#62]
I assume the way to modify or re-configure an existing indexer is to click the blue button/white wrench on the indexer. However, nothing happens when I do this. I've tried it in Chrome, Firefox and IE on Windows 7.

Thanks

P.S. love this app.

**Comment by Venxir** [comment]
I've fixed this in mij last pull request, hopefully online soon :)

**Comment by zone117x** [comment]
Just confirmed Venxir's implementation works, nice job :+1:
