### ISSUE TITLE
Freshon.tv - Configuration failed: incorrect string format

### ISSUE THREAD

**Issue by o0butch0o** [zone117x/Jackett#65]
After typing my freshon.tv username and password I get "Configuration failed: incorrect string format"

**Comment by nicolus** [comment]
If you're using windows, try setting the formatting to English United States) in the Region configuration, that fixed it for me, so I assume Jackett doesn't correctly handle various formats at the moment.

**Comment by o0butch0o** [comment]
It worked! Thanks!

**Comment by o0butch0o** [comment]
But it stopped working as soon a I put it back in canada... :(

**Comment by Kayomani** [comment]
This should be fixed in v0.5, the whole app defaults to the US region regardless of what the system is set to. Reopen if its still an issue.

**Comment by o0butch0o** [comment]
Yes! its fixed the problem! Thanks!!

Date: Sat, 25 Jul 2015 13:11:39 -0700
