### ISSUE TITLE
Morethan & Piratebay on Synology

### ISSUE THREAD

**Issue by sea3pea0** [zone117x/Jackett#66]
Has anyone managed to get morethan.tv and tpb working on synology? I installed libcurl dev and openssl-dev but still get "configuration failed: libcurl"  when trying to add morethan or tpb.

**Comment by zone117x** [comment]
@sea3pea0 can you give a brief explanation of how you got this to work? Then I'll link to this from the wiki and close this issue. Thanks

**Comment by sea3pea0** [comment]
To get Morethan & TPB working, I setup a chroot on my syno. I downloaded and followed the instructions here: https://github.com/fsquillace/junest . After setting up junest, I did the following: pacman -Sy mono, pacman -Sy curl, and pacman -S base-devel.

**Comment by zone117x** [comment]
Thanks https://github.com/zone117x/Jackett/wiki/Libcurl-on-Synology

**Comment by sea3pea0** [comment]
Your Welcome!
