### ISSUE TITLE
Wrong torrent size given to sonarr from thepiratebay indexer

### ISSUE THREAD

**Issue by Arvernien** [zone117x/Jackett#72]
I've found the pirate bay indexer is giving the wrong size of torrents to sonarr so it discards them for download. For example a 260 Mb torrent shows up in sonarr as a 25.7 Gb torrent. I have to manually select them for download making all the magic disappear :(

**Comment by damwthomas** [comment]
Could you give an example where you've encountered this problem (with what torrent search).

**Comment by zone117x** [comment]
I tested TPB and don't see any misreported file sizes. If you give an example torrent of where you're seeing this then I'll re-open the issue.

**Comment by Arvernien** [comment]
Sorry about the delay, too busy at work. For example this torrent:
https://thepiratebay.gd/torrent/11919932/Arrow.S03E23.HD.1080p.WEB-DL it's 1.74 Gb but Jackett gives the size of 174.0 Gb and when you check the info tab it says it has been rejected because "186.8 Gb is larger than maximum allowed":

![image](https://cloud.githubusercontent.com/assets/13052667/9568933/254fc382-4f5a-11e5-9f3e-21e545f54fb0.png)

Any thoughts? Thanks!
