### ISSUE TITLE
[REQ] Animebytes

### ISSUE THREAD

**Issue by blkphnx** [zone117x/Jackett#74]
Hi, It would be great if you can add support for Animebytes. It's arguably the best private tracker for Anime

**Comment by Kayomani** [comment]
I think I will have a fiddle and see what I can do,  there may need to be a certain amount of fudging involved for searching as AB only deal with full seasons.

**Comment by blkphnx** [comment]
Thanks a lot for the effort :+1:

**Comment by Kayomani** [comment]
I got a basic version working, took a bit more fiddling than I thought :o

Main thing stopping me delivering it currently is the fact that the site does not actually publish any of the torrent names.  That means when you do a search and add it to the torrent client sonarr can't match up the sonarr download and the torrent client download as the names are different, fortunately the torrents hash is available and can be used to match the two up.  I'll send them a pull request soon which will enable that, I don't see why it hasn't been done already tbh.

**Comment by zone117x** [comment]
Nice work @Kayomani  :+1:

**Comment by blkphnx** [comment]
Great job @Kayomani :+1:

**Comment by Kayomani** [comment]
The pull request was sent yesterday and is waiting on the Sonarr team.

I've finished the dev on this and testing it tonight I had a series download, track and import successfully :)

The code is on my fork if you are desperate for it / want to take a look, I'll send a pull request when they add my fix to Sonarr.

**Comment by Kayomani** [comment]
Merged to Jacket and fix merged to Sonarr develop.

There is an on going issue with series with a dot in them not matching but that will be another fix in Sonarr soon I would think.

**Comment by blkphnx** [comment]
Awesome. Thanks a lot. I will try this out tonight and let you know how it goes. :+1:
