### ISSUE TITLE
Freshon.tv torrents not adding to seedbox

### ISSUE THREAD

**Issue by piovere** [zone117x/Jackett#77]
I am using Jackett to connect a local Sonarr installation to a remote seedbox. Sonarr is able to add torrents from KickassTorrents (not using Jackett). Debug looks like Jackett is finding a release:

2015-07-05 16:17:41.1081 Debug Found 1 releases from FreshOnTV

but it doesn't add to the remote Transmission server

**Comment by zone117x** [comment]
Jackett finds releases and give them to Sonarr, Sonarr chooses which ones to download. This isn't an issue with Jackett.
