### ISSUE TITLE
Error adding indexer

### ISSUE THREAD

**Issue by my95z34** [zone117x/Jackett#8]
When clicking on the Okay button to add an indexer, a Toast message shows up at the bottom of the screen saying:
 
 Configuration failed: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure

Just looking for some input, thanks in advance!

**Comment by nthng** [comment]
Try running

`   mozroots --import --sync --machine `

first and then reboot. This will import all the root certificates, looks like a SSL problem.

**Comment by sea3pea0** [comment]
I have the same problem, that command doesn't work for me on synology. Any idea of a solution for archlinux?

**Comment by my95z34** [comment]
@nthng After running that, it still fails for me.  If it matters, I'm running on Ubuntu.

**Comment by zone117x** [comment]
I'm getting this on Ubuntu. Working on getting it fixed.

**Comment by my95z34** [comment]
@zone117x, sounds good, thanks!

**Comment by my95z34** [comment]
Just thought I'd chime in really quick.  I got Jackett set up inside of a Jail on my FreeNAS server and when adding a tracker there I get a different error.  Not sure if this is related or if I should start a new issue, or what.  But here it is!  lol

Configuration failed: Error: SendFailure (Error writing headers)

**Comment by nthng** [comment]
That one has to do with SSL, try running 'mozroots - - import - - sync - -
machine'. That one worked for me after a reboot.
Op 22 apr. 2015 06:06 schreef "my95z34" <notifications@github.com>:

**Comment by my95z34** [comment]
@nthng, still no go.  Restarted the jail after running command.  =\

**Comment by zone117x** [comment]
This should be fixed now. Libcurl is used for sites that have this ssl issue when running with mono. The readme has instructions for installation.
