### ISSUE TITLE
Investigate password char escaping on mono

### ISSUE THREAD

**Issue by zone117x** [zone117x/Jackett#83]
For example, a password of `i8#uPAy%7trr` for IPTorrents on linux may be causing issues.
@Mirabis

**Comment by zone117x** [comment]
Tested a similar password with IPTorrents on mono and it seems to work. This doesn't appear to be a problem. Closing issue.

**Comment by Mirabis** [comment]
Okay thx, tried it on 0.4.3 about an hour ago and didn't seem to work on my VM. Will try to resolve it with IPTorrents or on the distro's community. 

Can keep it closed :)

**Comment by zone117x** [comment]
@Mirabis some people are having trouble with IPT on mono because of SSL issues. We have an alpha release which may work for you: https://github.com/zone117x/Jackett/releases/tag/untagged-ba3df01805df6fdc48c5

**Comment by Mirabis** [comment]
Get a Page not found on that url

**Comment by zone117x** [comment]
Ah, we haven't made it public yet. Just compile from the master branch
