### ISSUE TITLE
MoreThan.TV stops working after reconfiguration

### ISSUE THREAD

**Issue by Mythic514** [zone117x/Jackett#84]
I noticed this problem recently, so I updated Jackett hoping a new version might fix it, but it's happening again. Essentially sonarr cannot search or download from MTV unless I reconfigure it. When I check the MTV setup in sonarr's settings everything looks normal, but when I test, it says there is a problem with the url. To fix the issue, I simply copy and paste the settings from Jackett into sonarr and everything works. Interestingly, the settings from Jackett and sonarr have not changed, as far as I can tell. Simply copying and pasting the identical information into sonarr fixes the issue (e.g. test works, and I can then search and download). However, this only fixes the problem for a short time (maybe a few hours or a day). After that, the issue resurfaces. This essentially means that I cannot automate downloading through MTV, unless I reconfigure settings ahead of time. Is there any way to fix this issue in the long term? I'd prefer to continue to primarily use MTV. Thanks.

**Comment by Kayomani** [comment]
This may get fixed by #97 will investigate further should this still be an issue after that is implemented.

**Comment by Kayomani** [comment]
Reopen if this is still an issue after upgrading to 0.5.
