### ISSUE TITLE
Torrent Leech add error

### ISSUE THREAD

**Issue by wookienz** [zone117x/Jackett#87]
Trying to add TL, get this error: 

Configuration failed: Error getting response stream (ReadDone1): ReceiveFailure

Fedora machine

**Comment by Kayomani** [comment]
Is this still an issue or was it a transient issue?

**Comment by wookienz** [comment]
Still not working a few days later

**Comment by Kayomani** [comment]
I have the same issue with the iptorrents tracker, looking into a workaround.

**Comment by zone117x** [comment]
Very likely related to SSL. Both these trackers work for me on Linux which means its not the TLS3.0 mono issue. Probably something to do with the root certificates installed on different machines.

**Comment by Kayomani** [comment]
Nah, curl works but libcurl doesn't and they'll use the same certs.

**Comment by zone117x** [comment]
Are there differences in the curl/libcurl/openssl versions?

**Comment by Kayomani** [comment]
Cant say i know how to check the libcurl version.  Annoyingly this has started working for me now, not sure what i changed to get it working in our code.  I have also implemented to /safecurl switch to just execute curl should people be using some problematic libcurl version.

Reopen should this still occur for you in v0.5.

**Comment by wookienz** [comment]
Is 0.5 released?

**Comment by Kayomani** [comment]
Later today hopefully.
