### ISSUE TITLE
No home directory (system user) causes crash

### ISSUE THREAD

**Issue by zone117x** [zone117x/Jackett#91]
https://github.com/zone117x/Jackett/issues/67#issuecomment-121751386

**Comment by Kayomani** [comment]
Where not running under linux and the normal directory is not writable perhaps use /etc/Jackett/ or similar.

**Comment by zone117x** [comment]
When creating a system user in Ubuntu (`sudo adduser --system testuser`), a home directory is created. For other systems that don't the user should know what they're doing and be responsible for creating the configuration directory. Closing this issue.
