### ISSUE TITLE
Category configuration?

### ISSUE THREAD

**Issue by evilhero** [zone117x/Jackett#93]
Is there anyway possible to allow for category definition without having to hard-code it within each provider file (using cat=94 (or whatever) doesn't seem to be working - at least for the sites I've tried it against)? 

I've had a request https://github.com/evilhero/mylar/issues/1089 to see if I could add in the ability to use torznab within my application, and it seems that the category definition is the only thing that's really hindering the use of it.

**Comment by Kayomani** [comment]
All the existing trackers will be hard coded to use the tv categories for Sonarr but in reality they should take the group id and match it to the groups that the tracker uses such as 7030.

http://newznab.readthedocs.org/en/latest/dev/lib/category/

**Comment by Kayomani** [comment]
Whilst doing searches by id rather than free text would be preferable most/all of the trackers we look at wouldn't be able to support it.  Have you any thoughts what trackers your user's might want, I am thinking we are best starting with IPT.

**Comment by evilhero** [comment]
Searching by ID would be great, but no torrent site would ever support that (save for 32p maybe, but they don't currently). The only private sites I know of that have any comics are IPT,  waffles and what. Starting with IPT would be good, plus then I could test out integration with my app which would make future additions easier.

**Comment by Kayomani** [comment]
I have changed IPT to be category aware and it seems to work quite well.  Either compile from develop or wait for the next release.

Example url localhost:9117/api/iptorrents?cat=8020&t=search&q=first

**Comment by evilhero** [comment]
Awesome work! I'll see if I can compile from source (I've had problems cause I run Ubuntu,  and it never works) - if not, I can at least start working on the provider code for torznab in my app until it gets pushed into your master branch.

Thanks for the quick work on this!

**Comment by zone117x** [comment]
The category mapping work from Kayomani is in the latest release. Closing this issue.
